#server setting
server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#Database연결
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  servlet:
    #multipart파일 업로드 용량
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB